### ISSUE TITLE
PowerJoy 84-in-1 (PJ-008) (Unl) [!] doesn't work

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#527] opened 2022-06-13 14:06 UTC
[PowerJoy 84-in-1 (PJ-008) (Unl) [!]](https://drive.google.com/file/d/1F58YoZS_cvl6fnGUr7lld0U1pVqYm8cm/view?usp=drivesdk)  has issue on FCEUX

PowerJoy 84-in-1 (PJ-008) (Unl) [!] mapper is Mapper 126

It fine works on other emulators

**Comment by vadosnaprimer** [comment] 2022-07-23 10:58
Duplicate of #479

**Closed by vadosnaprimer** 2022-07-23 10:58 UTC
