### ISSUE TITLE
Add Visible Sides option

### ISSUE THREAD

**Issue by SteveCraft28** [TASEmulators/fceux#542] opened 2022-07-19 13:58 UTC
The default is 256 sides

240 sides
![240 sides](https://user-images.githubusercontent.com/109541450/179767849-dee5ea49-e68c-49de-8088-4d8bcc63001a.png)
256 sides (default)
![256 sides](https://user-images.githubusercontent.com/109541450/179767901-389287ea-95c2-4ccb-9251-e1361730d36c.png)
272 sides
![272 sides](https://user-images.githubusercontent.com/109541450/179767989-507d26ea-3ef0-4def-b8bf-40ed9de692e7.png)
288 sides
![288 sides](https://user-images.githubusercontent.com/109541450/179768038-411ba2c0-3ed8-483e-856b-dee701e64418.png)
300 sides
![300 sides](https://user-images.githubusercontent.com/109541450/179768160-c4277ab7-59f1-493a-a397-39f9d10feff6.png)
320 sides
![320 sides](https://user-images.githubusercontent.com/109541450/179768234-008ff7e6-6f9a-470e-b6a9-ac0899f0476e.png)
426 sides
![426 sides](https://user-images.githubusercontent.com/109541450/179768310-62cf5829-7a33-4974-864a-07502f6ad452.png)
512 sides
![512 sides](https://user-images.githubusercontent.com/109541450/179768361-138fba6a-3db4-4b34-88c8-91aa0cf8df66.png)

**Comment by vadosnaprimer** [comment] 2022-07-23 10:33
Duplicate of #516

**Closed by vadosnaprimer** 2022-07-23 10:33 UTC
