### ISSUE TITLE
Duplicate requests:

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#505] opened 2022-05-12 14:50 UTC
Is it possible to add Famicom Expansion audios:

> Nintendo 2C33 (FDS Sound) On/Off

> Konami VRC6 On/Off

> Konami VRC7 On/Off

> Namco 163 (N163) On/Off

> Sunsoft 5B On/Off

> NEC µPD7755C (Jaleco) On/Off

> NEC µPD7756C (Jaleco) On/Off

> Mitsubishi M50805 (Bandai) On/Off

On FCEUX

Please add Famicom Expansion audios on/off on upcoming FCEUX 2.6.5

**Comment by vadosnaprimer** [comment] 2022-07-23 10:46
Duplicate of #490

**Closed by vadosnaprimer** 2022-07-23 10:46 UTC
