### ISSUE TITLE
Is it possible to implement FDS On/Off, MMC5 On/Off, VRC6 On/Off, VRC7 On/Off, N163 On/Off, S5B On/Off, EPSM On/Off audio sound mixer channels

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#534] opened 2022-07-06 05:44 UTC
Audio Sound Mixer Channel
> Square 1 On/Off
> Square 2 On/Off
> Triangle On/Off
> Noise On/Off
> PCM On/Off
> FDS On/Off
> MMC5 On/Off
> VRC6 On/Off
> VRC7 On/Off
> N163 On/Off
> S5B On/Off
> EPSM On/Off

**Comment by vadosnaprimer** [comment] 2022-07-23 10:35
Duplicate of #511

**Closed by vadosnaprimer** 2022-07-23 10:35 UTC
