### ISSUE TITLE
Add Famicom Sound Expansion On/Off In Audio Options

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#490] opened 2022-04-11 12:33 UTC
**FDS** Sound Expansion On/Off

**VRC6** Sound Expansion On/Off

**MMC5** Sound Expansion On/Off

**VRC7** Sound Expansion On/Off

**N163** Sound Expansion On/Off

**S5B** Sound Expansion On/Off

**Comment by vadosnaprimer** [comment] 2022-07-23 10:54
Duplicate of #483

**Closed by vadosnaprimer** 2022-07-23 10:54 UTC
