### ISSUE TITLE
[Feature request]: Add Famicom Expansion Sound Channels On/Off In Audio Options

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#492] opened 2022-04-17 10:28 UTC
**Nintendo FDS 2C33** On/Off
**Nintendo MMC5** On/Off
**Konami VRC6** On/Off
**Konami VRC7** On/Off
**Namco 163** On/Off
**Sunsoft 5B** On/Off
**NEC µPD7755C (Jaleco)** On/Off
**NEC µPD7756C (Jaleco)** On/Off
**Mitsubishi M50805 (Bandai)** On/Off

Add That Feature In **FCEUX, FCEUmm**

This Is Same About Added Square Wave 1 On/Off, Square Wave 2 On/Off, Triangle Wave On/Off, Noise On/Off, DPCM On/Off Sound Channel Feature In Audio Options.

**Comment by vadosnaprimer** [comment] 2022-07-23 10:46
Duplicate of #490

**Closed by vadosnaprimer** 2022-07-23 10:46 UTC
