### ISSUE TITLE
add FDS (Famicom Disk System) Sound Interpolation

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#531] opened 2022-06-28 10:22 UTC
@negativeExponent FDS (Famicom Disk System) Sound Interpolation means FDS Sound Emulation for example: Link no Bouken - The Legend of Zelda 2 death sound

add FDS Sound Interpolation:

> FCEUX
> REAL FDS
> EVERDRIVE N8

**Comment by vadosnaprimer** [comment] 2022-07-23 10:56
Duplicate of #476

**Closed by vadosnaprimer** 2022-07-23 10:56 UTC
