### ISSUE TITLE
Shift Key + Number or Symbol doesn't register as a keypress

### ISSUE THREAD

**Issue by calcwatch** [TASEmulators/fceux#464] opened 2022-02-20 23:25 UTC
**Describe the bug**

I noticed this when trying to use the Family Keyboard on FCEUX 2.6.1. When trying to type "shift + 1" to produce a "!", nothing happens. All number keys have this problem, as do symbol keys. (Example: "shift + /" doesn't work to produce a "?".)

This appears to be a deeper issue in `src/drivers/Qt/keyscan.cpp`. I've confirmed that it's a problem in macOS and Linux in the master branch. I'm using an English US keyboard, if that matters.

**To Reproduce**

To get to the crux of the issue, add this debug output to `src/drivers/Qt/keyscan.cpp` in `pushKeyEvent()`, right above `if (sdlev.key.keysym.scancode != SDL_SCANCODE_UNKNOWN)`:
```
printf("Qt key: %d, SDL key: %d, SDL scancode: %d\n", event->key(), sdlev.key.keysym.sym, sdlev.key.keysym.scancode);
``` 

Rebuild, run, click in the GUI and try key combos like "shift + 1", "shift + 2", etc. "Shift + 1" produces this output in the terminal:
```
Qt key: 33, SDL key: 33, SDL scancode: 0
```

Qt key 33 is `Key_Exclam` and SDL key 33 is `SDLK_EXCLAIM`, so that much is right. But "scancode 0" is `SDL_SCANCODE_UNKNOWN`, so the key event gets ignored.

I think I see what's going wrong. There is no "!" key, so there's no corresponding scancode. If I change `convQtKey2SDLKeyCode()` so that `Key_Exclam` maps to `SDLK_1`, I get the Family Keyboard behavior I want. But it's wrong to make assumptions like that, because they vary by keyboard. (For example "shift + 6" is "^" on my US keyboard, but it's "&" on a Japanese keyboard.) So I don't know what the general fix should be. I know that Qt has functions like `nativeVirtualKey()` that might help, but those aren't cross-platform solutions.

**Expected behavior**
Shifted numbers and symbols should produce appropriate scancodes.

**Screenshots**
N/A

**(please complete the following information):**
 - OS and Version: macOS 12.2 and Ubuntu 21.10
 - Version of FCEUX used: 2.6.2 (QT)

**Comment by mjbudd77** [comment] 2022-02-22 13:50
@calcwatch please try out the latest changes and let me know if this fixes your issue

**Comment by calcwatch** [comment] 2022-02-22 16:43
Thanks for looking into this! 

It fixes most of the issue. On my test ROM, shift now works with all the number and symbol keys, except for 3 and 6. "Shift + 3" had scancode 0x32 even before your fix, though it doesn't seem to do anything, and "shift + 6" still has scancode 0.

Strangely, Family BASIC still has a problem with all shifted numbers and symbols.

**Comment by mjbudd77** [comment] 2022-02-23 11:36
@calcwatch I've got a couple more updates for you to try. What test ROM are you using? I would like to try it myself.

**Comment by calcwatch** [comment] 2022-02-23 13:12
Yes, that fixes the remaining keys! By test ROM, I just meant a project I'm working on that uses the keyboard: https://github.com/calcwatch/nes64/releases

As for Family BASIC, it apparently doesn't like when both shift keys are pressed down. But FCEUX always does keypress events for left and right shift keys, regardless of the actual keypress. If I manually skip one of the shifts in `UpdateFKB()` in `src/drivers/Qt/input.cpp` (`x == 50` or `x == 62`), it works fine.

**Comment by mjbudd77** [comment] 2022-02-24 12:11
@calcwatch I've added the code to skip one of shift per your recommendation. Do you know if this sort of issue is also exists for the alt and ctrl keys? Currently the Qt GUI does not differentiate between left and right modifier keys. Qt doesn't give a great way to know which key is pressed as the functions that return native scancodes are not cross platform.

**Comment by calcwatch** [comment] 2022-02-27 14:13
I'm testing on a Mac, so there's only one ctrl key, but I have two "command" and "option" keys.

What I'm seeing is:
- Both command keys map to Famicom ctrl.
- The Mac ctrl key does nothing.
- Both option keys map to `GRPH` and `_`. I suspect that "option" is equivalent to PC "alt", left alt = `GRPH` and right alt = `_`. If so, this issue exists for alt as well.

I was inspired to write an actual keyboard test ROM, so this should help with debugging: https://github.com/calcwatch/nestests/releases/download/v0.1.0/keyboard_check.zip

Also, not directly related, but:
- There's no way to press "insert" on a Mac keyboard because they don't have insert keys anymore.
- I plugged in a PC USB keyboard and found that PC "Delete", "End" and "Page Down" map to Famicom "Home", "Insert" and "Delete" respectfully. "Insert" is supposed to map to "kana" according to the FCEUX docs, but nothing happens when I press it. (Maybe this is just weird Mac behavior with my PC keyboard, though.)

**Comment by mjbudd77** [comment] 2022-03-05 11:52
@calcwatch I think I've fixed all of the key mappings. I read that the insert key can used on mac with a fn + i key combination. Try it out and let me know.

**Comment by mjbudd77** [comment] 2022-03-06 03:22
@calcwatch I decided to add a virtual family keyboard dialog window to the Qt GUI. You can access it through the main emulation menu. What do you think?

**Comment by calcwatch** [comment] 2022-03-06 13:00
> @calcwatch I think I've fixed all of the key mappings. I read that the insert key can used on mac with a fn + i key combination. Try it out and let me know.

Great, they look better now! I think "fn + i" only works in apps that specifically support it; in FCEUX, it's the same as just pressing "i".

> @calcwatch I decided to add a virtual family keyboard dialog window to the Qt GUI. You can access it through the main emulation menu. What do you think?

I really like it! This helps me map keys like "kana" and "_" to keys that I have on my keyboard, and also allows me to have separate keys for left and right shift, so it resolves all of my issues. Just a few minor comments:

1. It's a bit confusing that you can bind "left shift" or "right shift" on the host machine to keys on the Famicom, but FCEUX still treats both of them as the same key event.
2. It says "Family Keyboard is disabled" when I first open it, but there's no explanation or option to enable it.
3. When I open the font config window, I get this warning:
```
2022-03-06 21:46:51.562 fceux[24587:1849268] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
```
4. _(Stress testing)_ It could use a maximum allowed font size. If I set the size to 1000, the keyboard config window can't be rendered anymore, and if I set it to 2000, the app crashes with:
```
Qt Warning: Failed to lock QIOSurfaceGraphicsBuffer(0x600002f326a0, surface=0x0, size=QSize(93674, 18367), isLocked=false, isInUse=false) -536870206 (:0, )
Qt Warning: Failed to lock QIOSurfaceGraphicsBuffer(0x600002f326a0, surface=0x0, size=QSize(93674, 18367), isLocked=false, isInUse=false) -536870206 (:0, )
zsh: illegal hardware instruction  ./src/fceux.app/Contents/MacOS/fceux
```

Thanks again for all the improvements!

**Comment by mjbudd77** [comment] 2022-03-07 03:09
I've added some more code to address most of what you have flagged. The font config window warning seems to be out of my control. If you believe that this is satisfactory, go ahead and close the issue.

**Comment by calcwatch** [comment] 2022-03-07 12:12
Sorry, just two more things I found:
1. The `_` key is associated with "Right Option", but both Option key events map to "Left Option", so there's no way to press it. (I can work around this by remapping the key manually.)
2. The keyboard dialog window randomly crashes. It seems to happen most often when I right click a key to remap its binding, and then click "cancel". (I'm building against Qt6, if it matters.)
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   fceux                         	       0x102ff002b FKBKeyMapDialog::enterButtonLoop() + 91 (FamilyKeyboard.cpp:1510)
1   fceux                         	       0x102feff4d FamilyKeyboardWidget::ctxMapPhysicalKey() + 93 (FamilyKeyboard.cpp:343)
2   fceux                         	       0x102e69a44 FamilyKeyboardWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 116 (moc_FamilyKeyboard.cpp:78)
3   QtCore                        	       0x1057a93f2 void doActivate<false>(QObject*, int, void**) + 1474
4   QtGui                         	       0x108a64a9d QAction::activate(QAction::ActionEvent) + 397
5   QtWidgets                     	       0x10816978d QMenuPrivate::activateCausedStack(QList<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool) + 77
6   QtWidgets                     	       0x108167228 QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 504
7   QtWidgets                     	       0x10816e5f0 QMenu::mouseReleaseEvent(QMouseEvent*) + 480
8   QtWidgets                     	       0x107ff4b67 QWidget::event(QEvent*) + 391
9   QtWidgets                     	       0x10816ed8e QMenu::event(QEvent*) + 1406
10  QtWidgets                     	       0x107fa0207 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
11  QtWidgets                     	       0x107fa297f QApplication::notify(QObject*, QEvent*) + 6159
12  QtCore                        	       0x1057580ea QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170
13  QtWidgets                     	       0x107fa09b7 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 935
14  QtWidgets                     	       0x10800bd66 QWidgetWindow::handleMouseEvent(QMouseEvent*) + 2662
15  QtWidgets                     	       0x10800a6eb QWidgetWindow::event(QEvent*) + 251
16  QtWidgets                     	       0x107fa0207 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
17  QtWidgets                     	       0x107fa1367 QApplication::notify(QObject*, QEvent*) + 503
18  QtCore                        	       0x1057580ea QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170
19  QtGui                         	       0x10872e830 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2352
20  QtGui                         	       0x10877c0ac QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 444
21  libqcocoa.dylib               	       0x10cf3270b QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 43
22  CoreFoundation                	    0x7ff80fcb78fd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
23  CoreFoundation                	    0x7ff80fcb7865 __CFRunLoopDoSource0 + 180
24  CoreFoundation                	    0x7ff80fcb75e4 __CFRunLoopDoSources0 + 242
25  CoreFoundation                	    0x7ff80fcb601b __CFRunLoopRun + 893
26  CoreFoundation                	    0x7ff80fcb55dd CFRunLoopRunSpecific + 563
27  HIToolbox                     	    0x7ff8188f24f1 RunCurrentEventLoopInMode + 292
28  HIToolbox                     	    0x7ff8188f2118 ReceiveNextEventCommon + 284
29  HIToolbox                     	    0x7ff8188f1fe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
30  AppKit                        	    0x7ff8126e4d88 _DPSNextEvent + 886
31  AppKit                        	    0x7ff8126e33f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
32  AppKit                        	    0x7ff8126d5919 -[NSApplication run] + 586
33  libqcocoa.dylib               	       0x10cf314fd QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2189
34  QtCore                        	       0x1057612d6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 454
35  QtWidgets                     	       0x10816d10e QMenuPrivate::exec(QPoint const&, QAction*, std::__1::function<QPoint (QSize const&)>) + 206
36  QtWidgets                     	       0x10816cff1 QMenu::exec(QPoint const&, QAction*) + 49
37  fceux                         	       0x102fefd97 FamilyKeyboardWidget::contextMenuEvent(QContextMenuEvent*) + 791 (FamilyKeyboard.cpp:333)
38  QtWidgets                     	       0x107ff50a6 QWidget::event(QEvent*) + 1734
39  QtWidgets                     	       0x107fa0207 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
40  QtWidgets                     	       0x107fa22f0 QApplication::notify(QObject*, QEvent*) + 4480
41  QtCore                        	       0x1057580ea QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170
42  QtWidgets                     	       0x10800bafc QWidgetWindow::handleMouseEvent(QMouseEvent*) + 2044
43  QtWidgets                     	       0x10800a6eb QWidgetWindow::event(QEvent*) + 251
44  QtWidgets                     	       0x107fa0207 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
45  QtWidgets                     	       0x107fa1367 QApplication::notify(QObject*, QEvent*) + 503
46  QtCore                        	       0x1057580ea QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170
47  QtGui                         	       0x10872e830 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2352
48  QtGui                         	       0x10877c0ac QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 444
49  libqcocoa.dylib               	       0x10cf3270b QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 43
50  CoreFoundation                	    0x7ff80fcb78fd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
51  CoreFoundation                	    0x7ff80fcb7865 __CFRunLoopDoSource0 + 180
52  CoreFoundation                	    0x7ff80fcb75e4 __CFRunLoopDoSources0 + 242
53  CoreFoundation                	    0x7ff80fcb601b __CFRunLoopRun + 893
54  CoreFoundation                	    0x7ff80fcb55dd CFRunLoopRunSpecific + 563
55  HIToolbox                     	    0x7ff8188f24f1 RunCurrentEventLoopInMode + 292
56  HIToolbox                     	    0x7ff8188f2118 ReceiveNextEventCommon + 284
57  HIToolbox                     	    0x7ff8188f1fe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
58  AppKit                        	    0x7ff8126e4d88 _DPSNextEvent + 886
59  AppKit                        	    0x7ff8126e33f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
60  AppKit                        	    0x7ff8126d5919 -[NSApplication run] + 586
61  libqcocoa.dylib               	       0x10cf314fd QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2189
62  QtCore                        	       0x1057612d6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 454
63  QtCore                        	       0x105758702 QCoreApplication::exec() + 130
64  fceux                         	       0x102f9fc66 main + 662 (main.cpp:166)
65  dyld                          	       0x1125d04fe start + 462
```

**Comment by calcwatch** [comment] 2022-03-07 12:28
And one more weird issue: Hold either shift down and press a letter key repeatedly. After a few letter key presses, the shift becomes unpressed. If I do this with the right shift key, sometimes a right shift key event briefly shows up.

**Comment by mjbudd77** [comment] 2022-03-09 01:17
I believe I've fixed the crash issue when hitting the cancel button. I cannot reproduce the issue with the option button. '_' seems to work fine with right option. I will look more into the shift issue.

**Comment by mjbudd77** [comment] 2022-03-10 02:28
I built against Qt6 on Mac OS and found that it is not returning the native key codes like Qt5 does. That is why right option button is not working.... once again Mac OS is my problem child. Linux and windows work fine.

**Comment by mjbudd77** [comment] 2022-03-18 16:36
Since the last part of this is a bug internal to Qt 6. Closing.

**Closed by mjbudd77** 2022-03-18 16:36 UTC
