### ISSUE TITLE
macOS Quitting doesn't quits

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#437] opened 2021-12-22 10:29 UTC
**Describe the bug**
After loading a ROM, File > Quit only closes the ROM.

**To Reproduce**
1. Open FCEUX
2. Open a ROM
3. File > Quit

**Expected behavior**
FCEUX quits after trying to quit by File > Quit

**Screenshots**
No

**(please complete the following information):**
 - OS and Version: macOS Big Sur 11.0
 - Version of FCEUX used (QT or non-QT): Qt FCEUX 2.5.0

**Additional context**
Windows 10 x64 Qt FCEUX 2.5.0 works

**Comment by meshuggahtas** [comment] 2021-12-22 10:30
The reproduction steps give me consistent error, exactly of what https://github.com/TASEmulators/fceux/issues/435 outputs

**Comment by mjbudd77** [comment] 2021-12-24 04:47
I believe this is now fixed. See recent commit b05e210982e378799cae9d724394f9cb2c87e22d

**Comment by meshuggahtas** [comment] 2021-12-25 14:40
OK, fixed. It worths mentioning that quitting through Quit takes a little bit more time than pressing X on the window. Quitting with Quit shows a blank (black) screen of fceux for less than 1 second. I can't measure it reliably because I already run it through VirtualBox but I believe this issue would be present on originally hosted macOSes.

I think you can close this issue, if this isn't a priority in the near future.

**Comment by mjbudd77** [comment] 2021-12-25 14:54
The 250 millisecond delay is by design. It is required to ensure that the event processing finishes before calling qApp->quit (). It was a recommendation that I saw online to ensure orderly shutdown. Since the delay is minimal and that is the price of stability, I’m ok with it.

**Closed by mjbudd77** 2021-12-25 14:54 UTC

**Comment by mjbudd77** [comment] 2021-12-25 16:25
I just thought of a couple ideas to hide the window to create the illusion of the window closing instantly. I will try it out later

**Comment by meshuggahtas** [comment] 2021-12-25 18:00
But how comes there is a difference? I mean pressing X and using Quit should terminate the same way. If a slower one is the more stable one, I guess it should be used for pressing X also.

**Comment by mjbudd77** [comment] 2021-12-25 18:05
Clicking the X generates a window close event that originates in the desktop environment. Using the menu generates an internal close window request.

**Comment by meshuggahtas** [comment] 2021-12-25 18:07
Ah makes sense. Thanks for the information anyways!
