### ISSUE TITLE
FCEUX 2.6.3 Update: Fix Gray Screen Bug On 115-in-1, 110-in-1 & Other

### ISSUE THREAD

**Issue by SopTheSop2022** [TASEmulators/fceux#467] opened 2022-03-04 20:15 UTC
Fix Gray Screen Bug On Some NES/FC Games: 115-in-1, 110-in-1 & Other
![hqdefault](https://user-images.githubusercontent.com/99989661/156834930-4ed5603d-ea14-4e1b-96f1-d66b0cf921f7.jpg)
@
![115-in-1-164x164](https://user-images.githubusercontent.com/99989661/156834959-ee4551df-8d70-4251-a21b-55fe4be4ea51.png)
![110in1menu](https://user-images.githubusercontent.com/99989661/156834976-768cd355-031c-41d9-9cc4-599f4865271b.png)

**Comment by negativeExponent** [comment] 2022-03-06 05:30
which mappers are these

**Comment by SopTheSop2022** [comment] 2022-03-06 20:16
MAP255

**Comment by negativeExponent** [comment] 2022-03-07 01:35
just to clarify, there is no official mapper 255 roms. anything that are mapper 255 are duplicate of mapper 225. You should edit the headers of your games and replace the mapper from 255 to 225.

I have also sent a PR that fixes some issues with these multicarts, aka 110-in-1 gray screen etc.

**Closed** 2022-03-07 02:49 UTC
