### ISSUE TITLE
Fix gray screen bug on PowerJoy 84-in-1 (PJ-008) (Unl) [!]

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#537] opened 2022-07-09 13:16 UTC
Fix gray screen bug on PowerJoy 84-in-1 (PJ-008) (Unl) [!]

![NES Gray Screen (PD) 000](https://user-images.githubusercontent.com/107685666/178107118-a2b2939d-b0e2-49f8-b850-dd57491d75f2.png)
![84 in 1](https://user-images.githubusercontent.com/107685666/178107119-8fe57106-5202-40d7-8393-e58bc0e9f569.png)

ROM Download to test on FCEUX: https://drive.google.com/file/d/1-TcN1c2s1Eu9DL1NDzWHDrdGBerZJpqQ/view?usp=drivesdk

File name: PowerJoy 84-in-1 (PJ-008) (Unl) [!]
MD5: 29337dc57dfeccf4a8004bc1f9bc88d3
SHA-1: 80cb7394e64d11bb4a6fe026a2e7349ca47ecccc
SHA-256: 1c74160bcd68be0151913d1b66d0be233585967d9029023f999037ee3655346b
Mapper: Mapper 126

**Comment by ReyVGM** [comment] 2022-07-12 08:25
You are ruining it for the rest of us.

You're the reason why the emulator authors don't even visit the github anymore. You've been told repeatedly that they are not going to work on unlicensed crap and you keep spamming about it.

**Comment by Squidward22** [comment] 2022-07-12 19:28
> You are ruining it for the rest of us.

> You're the reason why the emulator authors don't even visit the github anymore. You've been told repeatedly that they are not going to work on unlicensed crap and you keep spamming about it using multiple accounts.

> You are not fooling anyone and all you're doing is making the emulator authors ignore your requests even harder.

*What the heck?*

*I'm gonna again:*

**I tried PowerJoy 84-in-1 on FCEUX, It doesn't work. It works on Nestopia UE, FCEUmm, Mesen. Nestopia UE & Mesen are accuracy. It has Advanced Audio Settings; Square 1, Square 2, Triangle, Noise, DPCM, FDS, MMC5, VRC6, VRC7, N163, S5B. FCEUX: Square 1 On/Off, Square 2 On/Off, Triangle On/Off, Noise On/Off, DPCM On/Off**

**Comment by vadosnaprimer** [comment] 2022-07-23 10:30
Duplicate of #527

**Closed by vadosnaprimer** 2022-07-23 10:30 UTC
