### ISSUE TITLE
VT03 Games are not working on FCEUX

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#506] opened 2022-05-13 14:59 UTC
I found VT03 NES Games but it's not working on FCEUX. VT03 is 16-bit NES Famiclone graphics game but it's not working on FCEUX, Nestopia UE, Mesen, QuickNES, ViurtalNES and it says "failed to load game".

VT03 Games:
`Battlefield (Unl) (VT03).nes`

`Burrow (Unl) (VT03).nes`

`Discus Put (Unl) (VT03).nes`

`Dune War (Unl) (VT03).nes`

`Enchanter (Unl) (VT03).nes`

`Ghost Palace (Unl) (VT03).nes`

`Labyrinth (v2007SR01492) (Unl) (VT03).nes`

`Lucky Time (Unl) (VT03).nes`

`Memory Test (Unl) (VT03).nes`

`Shot Put (Unl) (VT03).nes`

`Silent Hunter (Unl) (VT03).nes`

`Sniper (Unl) (VT03).nes`

`Star (Unl) (VT03).nes`

`Star Attack (Unl) (VT03).nes`

`Sur LC (Unl) (VT03).nes`

Download VT03 Games: https://drive.google.com/file/d/1GQJ_ftpKWLbmIgY1L_iZt3YRvFxpZ8Qe/view?usp=drivesdk

Is it possible to add VT03 Support, 16-bit support.

**Comment by ClusterM** [comment] 2022-05-18 10:45
Actually these are not NES games, it's different hardware. So do not expect that support for it will be added.

**Comment by ClusterM** [comment] 2022-05-18 19:12
VT03 is based on NES but has many advanced features, it can handle much more colors.
Also, your ROMs are without headers at all.

**Comment by Squidward22** [comment] 2022-05-18 20:14
VT03 Mapper is called **Mapper 256, Mapper 407, Mapper 419, Mapper 425, Mapper 426**

**Comment by ClusterM** [comment] 2022-05-18 20:31
Mapper 256 is supported. But this is NOT NES colors:
![image](https://user-images.githubusercontent.com/4236181/169150265-4274998b-8532-4fd2-b2fa-bcf9f219431e.png)

![image](https://user-images.githubusercontent.com/4236181/169150285-ca8f3f6d-7625-4b2e-86e3-cac5a7d6e9e2.png)

![image](https://user-images.githubusercontent.com/4236181/169150334-c5a2b1ed-c5db-4fe6-adeb-7d7e0e531f65.png)

![image](https://user-images.githubusercontent.com/4236181/169150382-e9505959-e9f2-42e7-b6ac-715031f20b75.png)

![image](https://user-images.githubusercontent.com/4236181/169150422-c9c6ef3c-2068-46e6-b470-0b86e582e0b8.png)

**Comment by Squidward22** [comment] 2022-05-18 21:08
I'm sorry, but I'm using Android Phone/Tablet. NES Emulator For Android:

Nostalgia.NES (FCEUX 2.2.3)

NES.emu (1.5.59) (FCEUX 2.6.4)

MultiNESS GP (Nestopia UE)

NESoid (Old Version of FCE Ultra)

You Tested on EmuVT.

I Requesting to add Mapper 256, 407, 419, 425, 426 On FCEUX.

**Comment by SopTheSop27** [comment] 2022-06-07 12:45
Those are not NES/FC Games. They don't work on stock NES Hardware. I tried on EverDrive N8, I tried VT03 Collection on EverDrive N8, it says "unsupported mapper".

**Comment by Squidward22** [comment] 2022-07-16 18:49
VT03 is available on modified FCEUX (file extensions: .bin, .wxn, .nesm). FCEUX Modfied for Super Mario Bros. 1/3 (VT03) Hack (.nesm)

**Comment by SteveCraft28** [comment] 2022-07-20 11:30
VT03 only runs on a **"modified emulator"**

**Comment by vadosnaprimer** [comment] 2022-07-23 10:49
Duplicate of #481

**Closed by vadosnaprimer** 2022-07-23 10:49 UTC
