### ISSUE TITLE
[FCEUX 2.6.5 Update]: Add Famicom Expansion Sound Channels Audio On/Off

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#500] opened 2022-05-08 16:28 UTC
Add Famicom Expansion Sound Channels Audio On/Off

> Nintendo FDS 2C33 On/Off

> Nintendo MMC5 On/Off

> Konami VRC6 On/Off

> Konami VRC7 On/Off

> Namco 163 On/Off

> Sunsoft 5B On/Off

> NEC µPD7755C (Jaleco) On/Off

> NEC µPD7756C (Jaleco) On/Off

> Mitsubishi M50805 (Bandai) On/Off

**Comment by vadosnaprimer** [comment] 2022-07-23 10:46
Duplicate of #490

**Closed by vadosnaprimer** 2022-07-23 10:46 UTC
