### ISSUE TITLE
add Advanced Audio Settings

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#522] opened 2022-06-04 09:59 UTC
Is it possible to add Advanced Audio Settings like Nestopia UE

`Square 1 Channel Volume %`
(Modfy Square 1 Channel Volume %)

`Square 2 Channel Volume %`
(Modfy Square 2 Channel Volume %)

`Triangle Channel Volume %`
(Modfy Triangle Channel Volume %)

`Noise Channel Volume %`
(Modfy Noise Channel Volume %)

`DPCM Channel Volume %`
(Modfy DPCM Channel Volume %)

`FDS Channel Volume %`
(Modfy FDS Channel Volume %)

`MMC5 Channel Volume %`
(Modfy MMC5 Channel Volume %)

`VRC6 Channel Volume %`
(Modfy VRC6 Channel Volume %)

`VRC7 Channel Volume %`
(Modfy VRC7 Channel Volume %)

`N163 Channel Volume %`
(Modfy N163 Channel Volume %)

`S5B Channel Volume %`
(Modfy S5B Channel Volume %)

![Screenshot_20220604-114050~2](https://user-images.githubusercontent.com/105673473/171994467-7e3da93a-9d9a-4071-b5c9-ce7238358d43.jpg)
![Screenshot_20220604-114056~2](https://user-images.githubusercontent.com/105673473/171994470-c55e1246-4bb4-4991-beed-b4d7f1405727.jpg)

**Comment by vadosnaprimer** [comment] 2022-07-23 10:46
Duplicate of #490

**Closed by vadosnaprimer** 2022-07-23 10:46 UTC
