### ISSUE TITLE
Is it possible to add "Borders"

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#532] opened 2022-06-29 15:30 UTC
@negativeExponent is it possible to add "Borders" for example:

-16x pixels (288x240) (6:5)
![288](https://user-images.githubusercontent.com/107685666/176475812-ba24c352-de3f-4e1f-a2e2-b2d0816bbc7d.png)

-32x pixels (320x240) (4:3)
![External](https://user-images.githubusercontent.com/107685666/176476095-8cf4464f-9f36-4cd8-b8a5-3c48b9bfac87.png)

**Comment by vadosnaprimer** [comment] 2022-07-23 10:33
Duplicate of #516

**Closed by vadosnaprimer** 2022-07-23 10:33 UTC
